config/routes.rb
Testapp::Application.routes.draw do
  devise_for :users

  root :to => 'staticpage#index'

  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	attr_accessible :hour, :emotion, :learned, :image
  
  # Adding carrierwave uploader
  	mount_uploader :image, ImageUploader

	# Watch out - user is singular !
  	belongs_to :user
  	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

# Watch out, it is Pics, not Pic !
  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_filter :authenticate_user!, :only => [:new, :create]
	def index
		# All pictures visible to all
		@pics = Pic.all
		# Users only see their Pictures
		#@pics = current_user.pics.all
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = current_user.pics.create(params[:pic])
		redirect_to pics_path
	end

	def show
		@pic = Pic.find(params[:id])
	end

end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firehose NYC</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Request parameters inspector
<%= params.inspect %>
-->
<nav>
	<div class="navbar navbar-inverse">
	    <div class="navbar-inner">
		    <div class="container">
		     
		    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    </a>
		     
		    <!-- Be sure to leave the brand out there if you want it shown -->
		    <%= link_to 'Firehose NYC', root_path, :class => "brand" %> 
		    <!-- Everything you want hidden at 940px or less, place within here -->
		    <div class="nav-collapse collapse">

		    <ul class="nav">
		    	<li>
		    		<%= link_to 'Pictures App', pics_path %>
		    	</li>

		    	<!-- Display upload link only from Picture app -->
		    	<% if params[:controller].to_s == 'pics' %>
			    	<li>
			    		<%= link_to raw('<i class="icon-plus"></i> Picture'), new_pic_path %>
			    	</li>
		    	<% end %>
		    	<li>
		    		<%= link_to 'My Company', 'http://www.akamai.com', :target => "_new" , :confirm => "Leaving already?" %>
		    	</li>
			</ul>

			<ul class="nav pull-right">
				<% if user_signed_in? %>
					<li>
						<%= link_to current_user.email, edit_user_registration_path %>
					</li>
					<li>
						<%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete' %>
					</li>
				<% else %>
					<li>
						<%= link_to 'Sign Up', new_user_registration_path %>
					</li>
					<li>
						<%= link_to 'Sign In', new_user_session_path %>
					</li>
				<% end %>
			</ul>

		    </div>
		     
		    </div>
	    </div>
</div>
</nav>

<!-- Devise notice and alert section -->
<% if notice.present? %>
	<p class="notice label label-info pull-right"><%= notice %></p>
<% end %>
<% if alert.present? %>
	<p class="alert"><%= alert %></p>
<% end %>	

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<h2 class="custom-fonts text-center titlebox">These are my pictures</h2>

<div class="container">
	<div class="row">
		<% @pics.each do |pic| %>
		<div class="boxy span3">
			<div>
				<h2>
					Hour # <%= pic.hour %>
				</h2>

				<!-- Wrapping image with image_tag -->
				<p>
					<%= link_to pic_path(pic) do %>
						<%= image_tag pic.image.to_s %>
					<% end %>
				</p>
				<p>
					<%= pic.emotion %>
				</p>
				<p>
					I learned that
					<%= pic.learned %>
				</p>
				<% if pic.user.present? %>
				<p>
					<strong>Posted by :</strong> <%= pic.user.email %>
				</p>
				<% end %>
			</div>
		</div>

		<% end %>
	</div>
</div>

app/views/pics/new.html.erb
<div class="span6 offset3 text-center boxy">

	<h2 class="custom-font">Upload your stuff</h2>

	<%= simple_form_for @pic do |f|  %>
		<%= f.input :hour, :label => 'Required', :required => 'true', :placeholder => 'Which hour' %>

		<%= f.input :image, :as => :file %>
		
		<%= f.input :emotion, :label => 'How did you feel?', :required => 'true', :placeholder => 'Happy?' %>
		
		<%= f.input :learned, :label => 'What did you learned?', :input_html => {rows: '5'} %>

		<br />
		<%= submit_tag 'Submit', :class => "btn btn-success" %>
		<%= link_to 'Cancel', pics_path, :class => "btn btn-danger" %>
	<% end %>
</div>

app/views/pics/show.html.erb
<% if @pic.user.present? %>
	<h2 class="custom-fonts text-center titlebox">Picture posted by <%= @pic.user.email %></h2>
<% end %>
<div class="container">
	
		
		<div class="boxy text-center">
			
				<h2>
					Hour # <%= @pic.hour %>
				</h2>

				<!-- Wrapping image with image_tag -->
				<p>
					<%= image_tag @pic.image.to_s %>
				</p>
				<p>
					<%= @pic.emotion %>
				</p>
				<p>
					I learned that
					<%= @pic.learned %>
				</p>
		</div>

</div>

app/views/staticpage/index.html.erb
<html>
<head>
<title>Ruby on Rails Dev Weekend</title>
</head>
<body>

<div class="span6 offset3 text-center boxy custom-font">

	<h1>Kickass RoR App!</h1>
<p>
	Learning Ruby on Rails - Lesson 1: Installation is a bitch on Windows. Switch to linux.
</p>
<br />
<%= link_to 'Go NOW !', pics_path, :class => 'btn btn-danger btn-large' %>

</div>
</body>
</html>